[package]
name        = "kxpkg"
description = "Package Manager CLI for Kinetix libraries and applications"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true

[dependencies]
kinetix_lexer    = { workspace = true }
kinetix_parser   = { workspace = true }
kinetix_types    = { workspace = true }
kinetix_hir      = { workspace = true }
kinetix_codegen  = { workspace = true }
kinetix_vm       = { workspace = true }
kinetix_stdlib   = { workspace = true }
clap             = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
toml             = { workspace = true }
log              = { workspace = true }
env_logger       = { workspace = true }
