[package]
name        = "kinetix_lexer"
description = "Error-resilient tokenizer for the Kinetix programming language"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true

[dependencies]
thiserror     = { workspace = true }
unicode-width = { workspace = true }
smol_str      = { workspace = true }
